### ISSUE TITLE
Set custom network and consensus parameters

### ISSUE THREAD

**Issue by JBaczuk** [robinsage-dev/compchain#20]
These need to be split into different issues:
- [x] New network magic bytes #21 
- [x] New ports #22
- [x] New address prefixes #23
- [x] Activate BIPs immediately #24
- [x] New seeds #25
- [x] Clear checkpoint data #26
- [x] New distribution schedule #27 and subissues
