### ISSUE TITLE
Change distribution schedule

### ISSUE THREAD

**Issue by JBaczuk** [robinsage-dev/compchain#27]
Apply the following updates to coin distribution. These should be split into different issues:
- [x] 15 CC block rewards #31
- [x] 3 minutes block times #28 
- [x] 3 hour difficulty adjustment interval #29
- [x] 630,000 subsidy halving interval #30
- [x] 10% premine (2.1M) in spendable genesis coinbase #32
