### ISSUE TITLE
Rename bitcoin references to compchain

### ISSUE THREAD

**Issue by JBaczuk** [robinsage-dev/compchain#7]
These should be separated into different issues:
- [x] binaries from `bitcoind` to `compchaind` etc. #33
- [x] ticker from BTC to COCO #34
- [x] Rename BIP to CIP #35 (note not required for `v1.0.0`)
- [x] Documentation/Code comment references to Bitcoin -> Compchain, bitcoin -> compcoin, BTC -> COCO. #36
- [x] LICENSE and COPYRIGHT updates to add Compchain Core developers and years. #37
